
app:
  name: auth-api
  test: true

languageSystem:
  dir: 'C:/Users/super/PycharmProjects/auth_api/data/models'

voiceSystem:
  dir: 'C:/Users/super/PycharmProjects/auth_api/data/models/ubm_16_diag_13mfcc.pkl'
  border: 80

inputData:
  dinamicDir: 'C:/Users/super/PycharmProjects/auth_api/data/load_data'

inventory:
  dir: 'C:/Users/super/PycharmProjects/auth_api/data/users_data'
  voiceDirName: voice
  pswdDirName: pswd
